version: "3"

services:
  postgres:
    image: postgres:11.4
    container_name: workflow_postgres
    restart: always
    env_file:
      - ./.env.docker
    ports:
      - 5432:5432

  app:
    image: node:12
    deploy:
      replicas: 1
    env_file:
      - ./.env.docker
    container_name: koa-workflow_app
    restart: on-failure:10 # necessary due to possibility of postgres not being ready when service runs
    depends_on:
      - postgres
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    command: ./scripts/start_dev.sh
